### ISSUE TITLE
Morning session: Peer-to-peer code review

### ISSUE THREAD

**Issue by Banstein** [Bavon101/awesome_books#4]
Hi, @Bavon101 + @levy002 👋🏻,
Good job so far!

✅ No linter errors.
✅ You used the correct Github Flow.
✅ Good design look.

**Comment by Bavon101** [comment]
@Banstein Thanks for your feedback 🐱‍🏍

**Comment by ahangarha** [comment]
I do suggest to keep all the related functionality to the book collection inside the class.

The only thing we need to call from outside is to give data for new book. the rest can and I think should be handled inside the class. As an example you may look at [this code](https://github.com/ahangarha/Awesome-Books/blob/4a3cd23b2c19d42a060c588ebe2481dbdf086c11/index.js). Everything is in the class which makes it portable.
